version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nai1ka
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gymguru
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_network
  gymguru:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://nai1ka:123456@postgres:5432/gymguru
    ports:
      - "80:1234"
    depends_on:
      - postgres
    networks:
      - main_network
volumes:
  postgres_data:

networks:
  main_network:
    driver: bridge