version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gymguru
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_network
  gymguru:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER: true
      DB_LOGIN: ${DB_LOGIN}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "80:1234"
    depends_on:
      - postgres
    networks:
      - main_network
volumes:
  postgres_data:

networks:
  main_network:
    driver: bridge
