name: Build and Run Docker Image

on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: self-hosted
    env:
        DB_LOGIN: ${{ secrets.DB_LOGIN }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    
    steps:
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
        
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Test code
      run: |
        pytest tests/
      
    - name: Build Docker container
      run: docker compose build

    - name: Stop and remove existing container if it exists
      run: docker compose down

    - name: Run Docker container
      run: docker compose up -d

    - name: Check if site is available
      run: |
        sleep 5
        set -e
        url="localhost"

        response_code=$(curl --write-out "%{http_code}" --silent --output /dev/null "$url")
        
        if [ "$response_code" -eq 200 ]; then
          echo "Site is available"
        else
          echo "Site is not available"
          exit 1
        fi
     
