name: Build and Run Docker Image

on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker container
      run: docker compose build

    - name: Stop and remove existing container if it exists
      run: docker compose down

    - name: Run Docker container
      run: docker compose up -d
