name: Build and Run Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker container
      run: docker build -t nai1ka/gymguru:latest .

    - name: Stop and remove existing container if it exists
      run: |
        if [ $(docker ps -q -f name=gymguru) ]; then
          docker stop gymguru
          docker rm gymguru
        fi

        
    - name: Run Docker container
      run: docker run -d --name gymguru nai1ka/gymguru:latest
