name: Build and Run Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ice-lazurite960

    steps:
    
    - name: Build Docker container
      run: |
        docker build -t nai1ka/gymguru:latest .
        
    - name: Run Docker container
      run: |
        docker run -d --name gymguru nai1ka/gymguru:latest
