name: Build and Run Docker Image

on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker container
      run: docker build -t nai1ka/gymguru:latest .

    - name: Stop and remove existing container if it exists
      run: docker rm -f gymguru &>/dev/null && echo 'Removed old container'

    - name: Run Docker container
      run: docker run -p 80:1234 -d --name gymguru nai1ka/gymguru:latest
