name: Build and Run Docker Image

on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: self-hosted
    env:
        DB_LOGIN: ${{ secrets.DB_LOGIN }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    
    steps:
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
        
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      
    - name: Build Docker container
      run: docker compose build

    - name: Stop and remove existing container if it exists
      run: docker compose down

    - name: Run Docker container
      run: docker compose up -d
     
